baseurl = "https://rootsongjc.github.io/cloud-native-go"
languageCode = "en-us"
title = "Cloud Native Go"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Jimmy Song"
	description = "rootsongjc is Jimmy Song"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Cloud Native Go"

		[params.navigation.links]
			about     = "简介"
			services  = "收获"
			contact   = "联系方式"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Cloud Native Go"
		subtitle   = "<b>Building Web Applications and Microservices for the Cloud with Go and React</b> <br> <i>written by Kevin Hoffman and Dan Nemeth</i><br>translated to Chineses with ❤️ by four guys from [TalkingData](http://www.talkingdata.com)"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "关于本书"
		description = "在本书中，你将按照测试驱动和高度自动化的方式逐步实现基于Go的云原生应用程序构建。<br>本书涵盖构建服务的基本原理、中间件技术、git、Docker和Wercker等工具的使用，还包括云服务的配置。<br>涵盖了事件驱动源和CQRS等模式，书中的所有内容组合成最终的示例，可以为你自己的项目提供灵感。<br>[阅读简介](http://rootsongjc.github.io/talks/cloud-native-go/)"


	# Service section
	[params.services]
		headline = "从本书中你将学到什么？"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "云之道"
            description = "构建云原生应用的模式和原则"

        [[params.services.list]]
			icon = "fa-gamepad"
			title = "World of FluxCraft"
			description = "构建基于React的Web应用"

		[[params.services.list]]
            icon = "fa-server"
            title = "微服务"
            description = "在云上构建微服务的方法"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Golang"
            description = "Fall ❤️ with Go"

    # Aside section
	[params.aside]
		headline = "Jimmy Song's Blog"

		[params.aside.button]
			text = "Go"
			link = "http://rootsongjc.github.io"

	# Contact section
	[params.contact]
		headline = "与我联系"
		description = "对本书或对我本人感兴趣，请使用微信或邮件与我联系"
		phone = "jimmysong"
		email = "rootsongjc@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "37.007850"
	# 	longitude = "118.499305"
	# 	maps_api_key = ""
